server:
  servlet:
    context-path: /
  port: ${SERVER_PORT:8000}

management:
  server:
    port: 9090
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      slo:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 300ms, 500ms
      percentiles-histogram:
        "[http.server.requests]": true
spring:
  application:
    name: arch-intercessor
  main:
    banner-mode: off
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432}/${DATABASE_NAME:postgres}?currentSchema=${DATABASE_SCHEMA:public}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
  redis:
    host: ${REDIS_SERVER:redis}
    port: 6379
    password: ${REDIS_PASSWORD:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81}

logging:
  level:
    root: INFO
    org.springframework: INFO
    ru.gur.archintercessor: INFO

camunda.bpm:
  admin-user:
    id: ${CAMUNDA_ADMIN_ID:demo}
    password: ${CAMUNDA_ADMIN_PASSWORD:demo}
    firstName: ${CAMUNDA_ADMIN_FIRSTNAME:demo}
  filter:
    create: All tasks
  job-execution:
    enabled: true

app:
  kafka:
    enabled: true
  redis:
    enabled: true

kafka:
  bootstrapAddress: kafka:9094
  groupId: group1

interaction:
  profile:
    stubEnabled: false
    uri: ${PROFILES_URI:http://arch-profile-service.arch-gur.svc.cluster.local:9000}
  claim:
    stubEnabled: false
    uri: ${PROFILES_URI:http://arch-claim-service.arch-gur.svc.cluster.local:9000}
  agreement:
    stubEnabled: false
    uri: ${PROFILES_URI:http://arch-agreement-service.arch-gur.svc.cluster.local:9000}
  brokerageaccount:
    stubEnabled: false
    uri: ${PROFILES_URI:http://arch-brokerageaccount-service.arch-gur.svc.cluster.local:9000}
  documentgenerator:
    stubEnabled: false
    uri: ${PROFILES_URI:http://arch-documentgenerator-service.arch-gur.svc.cluster.local:9000}
  stoplist:
    stubEnabled: false
    uri: ${PROFILES_URI:http://arch-stoplist-service.arch-gur.svc.cluster.local:9000}
  productdictionary:
    stubEnabled: false
    uri: ${PROFILES_URI:http://arch-productdictionary-service.arch-gur.svc.cluster.local:9000}