server:
  servlet:
    context-path: /
  port: 8081

management:
  server:
    port: 9090
  endpoints:
    web:
      base-path: /
spring:
  datasource:
    url: jdbc:h2:mem:memdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: p
    driverClassName: org.h2.Driver
  h2:
    console:
      # http://localhost:8080/h2-console
      enabled: true
  main:
    banner-mode: CONSOLE
  redis:
    host: localhost
    port: 63792
    password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

logging:
  level:
    root: INFO
    org.springframework: INFO
    ru.gur.archintercessor: DEBUG

camunda:
  bpm:
    job-execution:
      enabled: true
    # http://localhost:8081/#/ excamad
    # http://localhost:8081/camunda/app/admin/default/#/
    admin-user:
      id: demo
      password: demo
      firstName: demo
    filter:
      create: All tasks

kafka:
  bootstrapAddress: localhost:9091
  groupId: group1

interaction:
  profile:
    stubEnabled: true
    uri: http://localhost:8180
  claim:
    stubEnabled: false
    uri: http://localhost:8281
  agreement:
    stubEnabled: true
    uri: http://localhost:8380
  brokerageaccount:
    stubEnabled: true
    uri: http://localhost:8480
  documentgenerator:
    stubEnabled: false
    uri: http://localhost:8580
  stoplist:
    stubEnabled: true
    uri: http://localhost:8680
  productdictionary:
    stubEnabled: true
    uri: http://localhost:8780

app:
  kafka:
    enabled: true
  redis:
    enabled: false

---

spring:
  profiles: test

interaction:
  profile:
    stubEnabled: true
  claim:
    stubEnabled: true
  agreement:
    stubEnabled: true
  brokerageaccount:
    stubEnabled: true
  documentgenerator:
    stubEnabled: true
  stoplist:
    stubEnabled: true
  productdictionary:
    stubEnabled: true
